/**
 * Use these fixtures for API responses in api.ts when doing offline local development
 */
export const players = {
  '4522': {
    totalAbilities: 1711,
    physique: { weight: 80, height: 185 },
    kitName: 'RONALDO',
    abilities: {
      catching: 40,
      explosivePower: 86,
      finishing: 95,
      kickingPower: 94,
      ballWinning: 57,
      swerve: 82,
      speed: 89,
      dribbling: 86,
      stamina: 89,
      injuryResistance: 2,
      ballControl: 91,
      form: 7,
      weakFootUsage: 2,
      coverage: 40,
      defensiveProwess: 49,
      goalkeeping: 40,
      lowPass: 83,
      placeKicking: 75,
      physicalContact: 87,
      attackingProwess: 94,
      reflexes: 40,
      clearing: 40,
      jump: 98,
      weakFootAccuracy: 3,
      bodyControl: 79,
      header: 94,
      loftedPass: 83
    },
    registeredPosition: 'LWF',
    playablePositions: {
      amf: 'B',
      rwf: 'A',
      lmf: 'A',
      cf: 'A',
      lwf: 'A',
      rmf: 'A',
      ss: 'A'
    },
    playerSkills: [
      'SCISSORS_FEINT',
      'FLIP_FLAP',
      'MARSEILLE_TURN',
      'CUT_BEHIND_TURN',
      'HEADING',
      'KNUCKLE_SHOT',
      'HEEL_TRICK',
      'FIRST_TIME_SHOT',
      'RABONA',
      'CAPTAINCY'
    ],
    appearance: {},
    commentaryId: '4522',
    nationality: 'PORTUGAL',
    comPlayingStyles: [
      'TRICKSTER',
      'MAZING_RUN',
      'SPEEDING_BULLET',
      'INCISIVE_RUN',
      'LONG_RANGER'
    ],
    name: 'C. RONALDO',
    motion: {
      hunchingRunning: 3,
      goalCelebration2: 109,
      hunchingDribbling: 3,
      armRunning: 4,
      armDribbling: 4,
      goalCelebration1: 109,
      penaltyKick: 3,
      cornerKick: 1,
      freeKick: 8
    },
    cardStats: { SPD: 89, PHY: 91, DEF: 67, DRI: 86, SHT: 94, PAS: 81 },
    id: '4522',
    isEdited: false,
    isBaseCopy: false,
    indexState: '2018-05-15T10:43:21.426Z',
    preferredFoot: 'RIGHT',
    playingStyle: 'PROLIFIC_WINGER',
    age: 32,
    ovr: 94
  },
  '7511': {
    name: 'L. MESSI',
    motion: {
      goalCelebration1: 66,
      penaltyKick: 1,
      cornerKick: 4,
      freeKick: 15,
      hunchingRunning: 1,
      goalCelebration2: 66,
      hunchingDribbling: 2,
      armRunning: 5,
      armDribbling: 5
    },
    cardStats: { DRI: 95, SHT: 90, PAS: 88, SPD: 86, PHY: 70, DEF: 53 },
    id: '7511',
    isEdited: false,
    isBaseCopy: false,
    indexState: '2018-05-15T10:43:21.426Z',
    preferredFoot: 'LEFT',
    playingStyle: 'CREATIVE_PLAYMAKER',
    age: 30,
    ovr: 98,
    totalAbilities: 1656,
    physique: { weight: 72, height: 170 },
    kitName: 'MESSI',
    abilities: {
      header: 68,
      loftedPass: 86,
      catching: 40,
      explosivePower: 92,
      finishing: 95,
      kickingPower: 80,
      ballWinning: 48,
      swerve: 89,
      speed: 86,
      dribbling: 96,
      stamina: 76,
      injuryResistance: 3,
      ballControl: 96,
      form: 7,
      weakFootUsage: 1,
      coverage: 40,
      defensiveProwess: 43,
      goalkeeping: 40,
      lowPass: 88,
      placeKicking: 90,
      physicalContact: 66,
      attackingProwess: 95,
      reflexes: 40,
      clearing: 40,
      jump: 67,
      weakFootAccuracy: 3,
      bodyControl: 95
    },
    registeredPosition: 'RWF',
    playablePositions: {
      ss: 'A',
      amf: 'A',
      rwf: 'A',
      lmf: 'B',
      cf: 'B',
      cmf: 'B',
      rmf: 'B'
    },
    playerSkills: [
      'MARSEILLE_TURN',
      'SOMBRERO',
      'CUT_BEHIND_TURN',
      'LONG_RANGE_DRIVE',
      'ACROBATIC_FINISHING',
      'FIRST_TIME_SHOT',
      'ONE_TOUCH_PASS',
      'PINPOINT_CROSSING',
      'LOW_LOFTED_PASS',
      'MALICIA'
    ],
    appearance: {},
    commentaryId: '7511',
    nationality: 'ARGENTINA',
    comPlayingStyles: [
      'MAZING_RUN',
      'SPEEDING_BULLET',
      'INCISIVE_RUN',
      'EARLY_CROSS'
    ]
  }
};
