import { Country } from '../service/api';

/** Lookup from `Country` enum to flag filename. */
export const CountryFlagImage = {
  [Country.AFGHANISTAN]: '/images/flags/afghanistan.png',
  [Country.ALBANIA]: '/images/flags/albania.png',
  [Country.ALGERIA]: '/images/flags/algeria.png',
  [Country.ANDORRA]: '/images/flags/andorra.png',
  [Country.ANGOLA]: '/images/flags/angola.png',
  [Country.ANTIGUA_AND_BARBUDA]: '/images/flags/antigua_and_barbuda.png',
  [Country.ARGENTINA]: '/images/flags/argentina.png',
  [Country.ARMENIA]: '/images/flags/armenia.png',
  [Country.ARUBA]: '/images/flags/aruba.png',
  [Country.AUSTRALIA]: '/images/flags/australia.png',
  [Country.AUSTRIA]: '/images/flags/austria.png',
  [Country.AZERBAIJAN]: '/images/flags/azerbaijan.png',
  [Country.BAHRAIN]: '/images/flags/bahrain.png',
  [Country.BANGLADESH]: '/images/flags/bangladesh.png',
  [Country.BARBADOS]: '/images/flags/barbados.png',
  [Country.BELARUS]: '/images/flags/belarus.png',
  [Country.BELGIUM]: '/images/flags/belgium.png',
  [Country.BENIN]: '/images/flags/benin.png',
  [Country.BERMUDA]: '/images/flags/bermuda.png',
  [Country.BOLIVIA]: '/images/flags/bolivia.png',
  [Country.BOSNIA_AND_HERZEGOVINA]: '/images/flags/bosnia.png',
  [Country.BOTSWANA]: '/images/flags/botswana.png',
  [Country.BRAZIL]: '/images/flags/brazil.png',
  [Country.BULGARIA]: '/images/flags/bulgaria.png',
  [Country.BURKINA_FASO]: '/images/flags/burkina_faso.png',
  [Country.BURUNDI]: '/images/flags/burundi.png',
  [Country.CAMEROON]: '/images/flags/cameroon.png',
  [Country.CANADA]: '/images/flags/canada.png',
  [Country.CAPE_VERDE]: '/images/flags/cape_verde.png',
  [Country.CENTRAL_AFRICAN_REP]: '/images/flags/central_african_rep.png',
  [Country.CHAD]: '/images/flags/chad.png',
  [Country.CHILE]: '/images/flags/chile.png',
  [Country.CHINA]: '/images/flags/china.png',
  [Country.COLOMBIA]: '/images/flags/colombia.png',
  [Country.CONGO]: '/images/flags/congo.png',
  [Country.CONGO_DR]: '/images/flags/congo_dr.png',
  [Country.COSTA_RICA]: '/images/flags/costa_rica.png',
  [Country.COTE_D_IVOIRE]: '/images/flags/cote_d_ivoire.png',
  [Country.CROATIA]: '/images/flags/croatia.png',
  [Country.CUBA]: '/images/flags/cuba.png',
  [Country.CURACAO]: '/images/flags/curacao.png',
  [Country.CYPRUS]: '/images/flags/cyprus.png',
  [Country.CZECH_REPUBLIC]: '/images/flags/czech_republic.png',
  [Country.DENMARK]: '/images/flags/denmark.png',
  [Country.DOMINICAN_REPUBLIC]: '/images/flags/dominican_republic.png',
  [Country.ECUADOR]: '/images/flags/ecuador.png',
  [Country.EGYPT]: '/images/flags/egypt.png',
  [Country.EL_SALVADOR]: '/images/flags/el_salvador.png',
  [Country.ENGLAND]: '/images/flags/england.png',
  [Country.EQUATORIAL_GUINEA]: '/images/flags/equatorial_guinea.png',
  [Country.ERITREA]: '/images/flags/eritrea.png',
  [Country.ESTONIA]: '/images/flags/estonia.png',
  [Country.ETHIOPIA]: '/images/flags/ethiopia.png',
  [Country.FAROE_ISLANDS]: '/images/flags/faroe_islands.png',
  [Country.FIJI]: '/images/flags/fiji.png',
  [Country.FINLAND]: '/images/flags/finland.png',
  [Country.FRANCE]: '/images/flags/france.png',
  [Country.FRENCH_GUIANA]: '/images/flags/french_guiana.png',
  [Country.GABON]: '/images/flags/gabon.png',
  [Country.GEORGIA]: '/images/flags/georgia.png',
  [Country.GERMANY]: '/images/flags/germany.png',
  [Country.GHANA]: '/images/flags/ghana.png',
  [Country.GREECE]: '/images/flags/greece.png',
  [Country.GRENADA]: '/images/flags/grenada.png',
  [Country.GUADELOUPE]: '/images/flags/guadeloupe.png',
  [Country.GUATEMALA]: '/images/flags/guatemala.png',
  [Country.GUINEA]: '/images/flags/guinea.png',
  [Country.GUINEA_BISSAU]: '/images/flags/guinea_bissau.png',
  [Country.GUYANA]: '/images/flags/guyana.png',
  [Country.HAITI]: '/images/flags/haiti.png',
  [Country.HONDURAS]: '/images/flags/honduras.png',
  [Country.HUNGARY]: '/images/flags/hungary.png',
  [Country.ICELAND]: '/images/flags/iceland.png',
  [Country.INDIA]: '/images/flags/india.png',
  [Country.INDONESIA]: '/images/flags/indonesia.png',
  [Country.IRAN]: '/images/flags/iran.png',
  [Country.IRAQ]: '/images/flags/iraq.png',
  [Country.IRELAND]: '/images/flags/ireland.png',
  [Country.ISRAEL]: '/images/flags/israel.png',
  [Country.ITALY]: '/images/flags/italy.png',
  [Country.JAMAICA]: '/images/flags/jamaica.png',
  [Country.JAPAN]: '/images/flags/japan.png',
  [Country.JORDAN]: '/images/flags/jordan.png',
  [Country.KAZAKHSTAN]: '/images/flags/kazakhstan.png',
  [Country.KENYA]: '/images/flags/kenya.png',
  [Country.KOSOVO]: '/images/flags/kosovo.png',
  [Country.KUWAIT]: '/images/flags/kuwait.png',
  [Country.KYRGYZ_REPUBLIC]: '/images/flags/kyrgyz_republic.png',
  [Country.LAOS]: '/images/flags/laos.png',
  [Country.LATVIA]: '/images/flags/latvia.png',
  [Country.LEBANON]: '/images/flags/lebanon.png',
  [Country.LIBERIA]: '/images/flags/liberia.png',
  [Country.LIBYA]: '/images/flags/libya.png',
  [Country.LIECHTENSTEIN]: '/images/flags/liechtenstein.png',
  [Country.LITHUANIA]: '/images/flags/lithuania.png',
  [Country.LUXEMBOURG]: '/images/flags/luxembourg.png',
  [Country.MACEDONIA]: '/images/flags/macedonia.png',
  [Country.MADAGASCAR]: '/images/flags/madagascar.png',
  [Country.MALAWI]: '/images/flags/malawi.png',
  [Country.MALAYSIA]: '/images/flags/malaysia.png',
  [Country.MALDIVES]: '/images/flags/maldives.png',
  [Country.MALI]: '/images/flags/mali.png',
  [Country.MALTA]: '/images/flags/malta.png',
  [Country.MARTINIQUE]: '/images/flags/martinique.png',
  [Country.MAURITANIA]: '/images/flags/mauritania.png',
  [Country.MAURITIUS]: '/images/flags/mauritius.png',
  [Country.MEXICO]: '/images/flags/mexico.png',
  [Country.MOLDOVA]: '/images/flags/moldova.png',
  [Country.MONACO]: '/images/flags/monaco.png',
  [Country.MONTENEGRO]: '/images/flags/montenegro.png',
  [Country.MONTSERRAT]: '/images/flags/montserrat.png',
  [Country.MOROCCO]: '/images/flags/morocco.png',
  [Country.MOZAMBIQUE]: '/images/flags/mozambique.png',
  [Country.NAMIBIA]: '/images/flags/namibia.png',
  [Country.NETHERLANDS]: '/images/flags/netherlands.png',
  [Country.NETHERLANDS_ANTILLES]: '/images/flags/netherlands_antilles.png',
  [Country.NEW_CALEDONIA]: '/images/flags/new_caledonia.png',
  [Country.NEW_ZEALAND]: '/images/flags/new_zealand.png',
  [Country.NIGER]: '/images/flags/niger.png',
  [Country.NIGERIA]: '/images/flags/nigeria.png',
  [Country.NORTH_KOREA]: '/images/flags/north_korea.png',
  [Country.NORTHERN_IRELAND]: '/images/flags/northern_ireland.png',
  [Country.NORWAY]: '/images/flags/norway.png',
  [Country.OMAN]: '/images/flags/oman.png',
  [Country.OTHERS]: '/images/flags/others.png',
  [Country.PAKISTAN]: '/images/flags/pakistan.png',
  [Country.PALESTINE]: '/images/flags/palestine.png',
  [Country.PANAMA]: '/images/flags/panama.png',
  [Country.PAPUA_NEW_GUINEA]: '/images/flags/papua_new_guinea.png',
  [Country.PARAGUAY]: '/images/flags/paraguay.png',
  [Country.PERU]: '/images/flags/peru.png',
  [Country.PHILIPPINES]: '/images/flags/philippines.png',
  [Country.POLAND]: '/images/flags/poland.png',
  [Country.PORTUGAL]: '/images/flags/portugal.png',
  [Country.PUERTO_RICO]: '/images/flags/puerto_rico.png',
  [Country.QATAR]: '/images/flags/qatar.png',
  [Country.REPUBLIC_OF_THE_GAMBIA]: '/images/flags/republic_of_the_gambia.png',
  [Country.REUNION]: '/images/flags/reunion.png',
  [Country.ROMANIA]: '/images/flags/romania.png',
  [Country.RUSSIA]: '/images/flags/russia.png',
  [Country.RWANDA]: '/images/flags/rwanda.png',
  [Country.SAMOA]: '/images/flags/samoa.png',
  [Country.SAN_MARINO]: '/images/flags/san_marino.png',
  [Country.SAUDI_ARABIA]: '/images/flags/saudi_arabia.png',
  [Country.SCOTLAND]: '/images/flags/scotland.png',
  [Country.SENEGAL]: '/images/flags/senegal.png',
  [Country.SERBIA]: '/images/flags/serbia_and_montenegro.png',
  [Country.SIERRA_LEONE]: '/images/flags/sierra_leone.png',
  [Country.SINGAPORE]: '/images/flags/singapore.png',
  [Country.SINT_MAARTEN]: '/images/flags/sint_maarten.png',
  [Country.SLOVAKIA]: '/images/flags/slovakia.png',
  [Country.SLOVENIA]: '/images/flags/slovenia.png',
  [Country.SOLOMON_ISLANDS]: '/images/flags/solomon_islands.png',
  [Country.SOMALIA]: '/images/flags/somalia.png',
  [Country.SOUTH_AFRICA]: '/images/flags/south_africa.png',
  [Country.SOUTH_KOREA]: '/images/flags/south_korea.png',
  [Country.SOUTH_SUDAN]: '/images/flags/south_sudan.png',
  [Country.SPAIN]: '/images/flags/spain.png',
  [Country.SRI_LANKA]: '/images/flags/sri_lanka.png',
  [Country.SUDAN]: '/images/flags/sudan.png',
  [Country.SWEDEN]: '/images/flags/sweden.png',
  [Country.SWITZERLAND]: '/images/flags/switzerland.png',
  [Country.SYRIA]: '/images/flags/syria.png',
  [Country.TAHITI]: '/images/flags/tahiti.png',
  [Country.TAIWAN]: '/images/flags/taiwan.png',
  [Country.TAJIKISTAN]: '/images/flags/tajikistan.png',
  [Country.THAILAND]: '/images/flags/thailand.png',
  [Country.THE_COMOROS]: '/images/flags/the_comoros.png',
  [Country.TOGO]: '/images/flags/togo.png',
  [Country.TRINIDAD_AND_TOBAGO]: '/images/flags/trinidad_and_tobago.png',
  [Country.TUNISIA]: '/images/flags/tunisia.png',
  [Country.TURKEY]: '/images/flags/turkey.png',
  [Country.TURKMENISTAN]: '/images/flags/turkmenistan.png',
  [Country.TURKS_AND_CAICOS_IS]: '/images/flags/turks_and_caicos_is.png',
  [Country.UAE]: '/images/flags/uae.png',
  [Country.UGANDA]: '/images/flags/uganda.png',
  [Country.UKRAINE]: '/images/flags/ukraine.png',
  [Country.UNITED_STATES]: '/images/flags/united_states.png',
  [Country.URUGUAY]: '/images/flags/uruguay.png',
  [Country.UZBEKISTAN]: '/images/flags/uzbekistan.png',
  [Country.VENEZUELA]: '/images/flags/venezuela.png',
  [Country.VIETNAM]: '/images/flags/vietnam.png',
  [Country.WALES]: '/images/flags/wales.png',
  [Country.ZAMBIA]: '/images/flags/zambia.png',
  [Country.ZIMBABWE]: '/images/flags/zimbabwe.png'
};

export const CountryLabel = {
  [Country.AFGHANISTAN]: 'Afghanistan',
  [Country.ALBANIA]: 'Albania',
  [Country.ALGERIA]: 'Algeria',
  [Country.ANDORRA]: 'Andorra',
  [Country.ANGOLA]: 'Angola',
  [Country.ANTIGUA_AND_BARBUDA]: 'Antigua and barbuda',
  [Country.ARGENTINA]: 'Argentina',
  [Country.ARMENIA]: 'Armenia',
  [Country.ARUBA]: 'Aruba',
  [Country.AUSTRALIA]: 'Australia',
  [Country.AUSTRIA]: 'Austria',
  [Country.AZERBAIJAN]: 'Azerbaijan',
  [Country.BAHRAIN]: 'Bahrain',
  [Country.BANGLADESH]: 'Bangladesh',
  [Country.BARBADOS]: 'Barbados',
  [Country.BELARUS]: 'Belarus',
  [Country.BELGIUM]: 'Belgium',
  [Country.BENIN]: 'Benin',
  [Country.BERMUDA]: 'Bermuda',
  [Country.BOLIVIA]: 'Bolivia',
  [Country.BOSNIA_AND_HERZEGOVINA]: 'Bosnia and herzegovina',
  [Country.BOTSWANA]: 'Botswana',
  [Country.BRAZIL]: 'Brazil',
  [Country.BULGARIA]: 'Bulgaria',
  [Country.BURKINA_FASO]: 'Burkina faso',
  [Country.BURUNDI]: 'Burundi',
  [Country.CAMEROON]: 'Cameroon',
  [Country.CANADA]: 'Canada',
  [Country.CAPE_VERDE]: 'Cape verde',
  [Country.CENTRAL_AFRICAN_REP]: 'Central african rep',
  [Country.CHAD]: 'Chad',
  [Country.CHILE]: 'Chile',
  [Country.CHINA]: 'China',
  [Country.COLOMBIA]: 'Colombia',
  [Country.CONGO]: 'Congo',
  [Country.CONGO_DR]: 'Congo dr',
  [Country.COSTA_RICA]: 'Costa rica',
  [Country.COTE_D_IVOIRE]: 'Cote d ivoire',
  [Country.CROATIA]: 'Croatia',
  [Country.CUBA]: 'Cuba',
  [Country.CURACAO]: 'Curacao',
  [Country.CYPRUS]: 'Cyprus',
  [Country.CZECH_REPUBLIC]: 'Czech republic',
  [Country.DENMARK]: 'Denmark',
  [Country.DOMINICAN_REPUBLIC]: 'Dominican republic',
  [Country.ECUADOR]: 'Ecuador',
  [Country.EGYPT]: 'Egypt',
  [Country.EL_SALVADOR]: 'El salvador',
  [Country.ENGLAND]: 'England',
  [Country.EQUATORIAL_GUINEA]: 'Equatorial guinea',
  [Country.ERITREA]: 'Eritrea',
  [Country.ESTONIA]: 'Estonia',
  [Country.ETHIOPIA]: 'Ethiopia',
  [Country.FAROE_ISLANDS]: 'Faroe islands',
  [Country.FIJI]: 'Fiji',
  [Country.FINLAND]: 'Finland',
  [Country.FRANCE]: 'France',
  [Country.FRENCH_GUIANA]: 'French guiana',
  [Country.GABON]: 'Gabon',
  [Country.GEORGIA]: 'Georgia',
  [Country.GERMANY]: 'Germany',
  [Country.GHANA]: 'Ghana',
  [Country.GREECE]: 'Greece',
  [Country.GRENADA]: 'Grenada',
  [Country.GUADELOUPE]: 'Guadeloupe',
  [Country.GUATEMALA]: 'Guatemala',
  [Country.GUINEA]: 'Guinea',
  [Country.GUINEA_BISSAU]: 'Guinea bissau',
  [Country.GUYANA]: 'Guyana',
  [Country.HAITI]: 'Haiti',
  [Country.HONDURAS]: 'Honduras',
  [Country.HUNGARY]: 'Hungary',
  [Country.ICELAND]: 'Iceland',
  [Country.INDIA]: 'India',
  [Country.INDONESIA]: 'Indonesia',
  [Country.IRAN]: 'Iran',
  [Country.IRAQ]: 'Iraq',
  [Country.IRELAND]: 'Ireland',
  [Country.ISRAEL]: 'Israel',
  [Country.ITALY]: 'Italy',
  [Country.JAMAICA]: 'Jamaica',
  [Country.JAPAN]: 'Japan',
  [Country.JORDAN]: 'Jordan',
  [Country.KAZAKHSTAN]: 'Kazakhstan',
  [Country.KENYA]: 'Kenya',
  [Country.KOSOVO]: 'Kosovo',
  [Country.KUWAIT]: 'Kuwait',
  [Country.KYRGYZ_REPUBLIC]: 'Kyrgyz republic',
  [Country.LAOS]: 'Laos',
  [Country.LATVIA]: 'Latvia',
  [Country.LEBANON]: 'Lebanon',
  [Country.LIBERIA]: 'Liberia',
  [Country.LIBYA]: 'Libya',
  [Country.LIECHTENSTEIN]: 'Liechtenstein',
  [Country.LITHUANIA]: 'Lithuania',
  [Country.LUXEMBOURG]: 'Luxembourg',
  [Country.MACEDONIA]: 'Macedonia',
  [Country.MADAGASCAR]: 'Madagascar',
  [Country.MALAWI]: 'Malawi',
  [Country.MALAYSIA]: 'Malaysia',
  [Country.MALDIVES]: 'Maldives',
  [Country.MALI]: 'Mali',
  [Country.MALTA]: 'Malta',
  [Country.MARTINIQUE]: 'Martinique',
  [Country.MAURITANIA]: 'Mauritania',
  [Country.MAURITIUS]: 'Mauritius',
  [Country.MEXICO]: 'Mexico',
  [Country.MOLDOVA]: 'Moldova',
  [Country.MONACO]: 'Monaco',
  [Country.MONTENEGRO]: 'Montenegro',
  [Country.MONTSERRAT]: 'Montserrat',
  [Country.MOROCCO]: 'Morocco',
  [Country.MOZAMBIQUE]: 'Mozambique',
  [Country.NAMIBIA]: 'Namibia',
  [Country.NETHERLANDS]: 'Netherlands',
  [Country.NETHERLANDS_ANTILLES]: 'Netherlands antilles',
  [Country.NEW_CALEDONIA]: 'New caledonia',
  [Country.NEW_ZEALAND]: 'New zealand',
  [Country.NIGER]: 'Niger',
  [Country.NIGERIA]: 'Nigeria',
  [Country.NORTH_KOREA]: 'North korea',
  [Country.NORTHERN_IRELAND]: 'Northern ireland',
  [Country.NORWAY]: 'Norway',
  [Country.OMAN]: 'Oman',
  [Country.OTHERS]: 'Others',
  [Country.PAKISTAN]: 'Pakistan',
  [Country.PALESTINE]: 'Palestine',
  [Country.PANAMA]: 'Panama',
  [Country.PAPUA_NEW_GUINEA]: 'Papua new guinea',
  [Country.PARAGUAY]: 'Paraguay',
  [Country.PERU]: 'Peru',
  [Country.PHILIPPINES]: 'Philippines',
  [Country.POLAND]: 'Poland',
  [Country.PORTUGAL]: 'Portugal',
  [Country.PUERTO_RICO]: 'Puerto rico',
  [Country.QATAR]: 'Qatar',
  [Country.REPUBLIC_OF_THE_GAMBIA]: 'Republic of the gambia',
  [Country.REUNION]: 'Reunion',
  [Country.ROMANIA]: 'Romania',
  [Country.RUSSIA]: 'Russia',
  [Country.RWANDA]: 'Rwanda',
  [Country.SAMOA]: 'Samoa',
  [Country.SAN_MARINO]: 'San marino',
  [Country.SAUDI_ARABIA]: 'Saudi arabia',
  [Country.SCOTLAND]: 'Scotland',
  [Country.SENEGAL]: 'Senegal',
  [Country.SERBIA]: 'Serbia',
  [Country.SIERRA_LEONE]: 'Sierra leone',
  [Country.SINGAPORE]: 'Singapore',
  [Country.SINT_MAARTEN]: 'Sint maarten',
  [Country.SLOVAKIA]: 'Slovakia',
  [Country.SLOVENIA]: 'Slovenia',
  [Country.SOLOMON_ISLANDS]: 'Solomon islands',
  [Country.SOMALIA]: 'Somalia',
  [Country.SOUTH_AFRICA]: 'South africa',
  [Country.SOUTH_KOREA]: 'South korea',
  [Country.SOUTH_SUDAN]: 'South sudan',
  [Country.SPAIN]: 'Spain',
  [Country.SRI_LANKA]: 'Sri lanka',
  [Country.SUDAN]: 'Sudan',
  [Country.SWEDEN]: 'Sweden',
  [Country.SWITZERLAND]: 'Switzerland',
  [Country.SYRIA]: 'Syria',
  [Country.TAHITI]: 'Tahiti',
  [Country.TAIWAN]: 'Taiwan',
  [Country.TAJIKISTAN]: 'Tajikistan',
  [Country.THAILAND]: 'Thailand',
  [Country.THE_COMOROS]: 'The comoros',
  [Country.TOGO]: 'Togo',
  [Country.TRINIDAD_AND_TOBAGO]: 'Trinidad and tobago',
  [Country.TUNISIA]: 'Tunisia',
  [Country.TURKEY]: 'Turkey',
  [Country.TURKMENISTAN]: 'Turkmenistan',
  [Country.TURKS_AND_CAICOS_IS]: 'Turks and caicos is',
  [Country.UAE]: 'Uae',
  [Country.UGANDA]: 'Uganda',
  [Country.UKRAINE]: 'Ukraine',
  [Country.UNITED_STATES]: 'United states',
  [Country.URUGUAY]: 'Uruguay',
  [Country.UZBEKISTAN]: 'Uzbekistan',
  [Country.VENEZUELA]: 'Venezuela',
  [Country.VIETNAM]: 'Vietnam',
  [Country.WALES]: 'Wales',
  [Country.ZAMBIA]: 'Zambia',
  [Country.ZIMBABWE]: 'Zimbabwe'
};
